name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to push to github

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          persist-credentials: true

      - name: Setup pnpm
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          version: ^11.0.0
          runtime: node@latest

      - name: Build
        run: pnpm run build

      - name: Deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin deploy

          git worktree add deploy-worktree deploy

          rm -rf deploy-worktree/*
          cp -r dist/* deploy-worktree/

          cd deploy-worktree
          git add .
          git commit -m "deploy" || echo "no changes"
          git push origin deploy
